#pragma once

#include "..\Core.h"

#include <windows.h>
#include <gl/gl.h>
#include "GLHeaders/glext.h"
#include "GLHeaders/wglext.h"
#include "GLHeaders/glcorearb.h"

#pragma comment (lib, "opengl32.lib")

#define LOAD_GL_FUNC(x, p) x = reinterpret_cast<p>(wglGetProcAddress(#x)); \
					if (x == nullptr) { MessageBoxA(NULL, #x, "Error loading OpenGL function", MB_OK); return false;}

static bool ModernOpenGLLoaded = false;

// Loaded at window creation
extern PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB;
extern PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;

// Loaded by call to LoadModernOpenGL()
extern PFNGLCREATEPROGRAMPROC glCreateProgram;
extern PFNGLCREATESHADERPROC glCreateShader;
extern PFNGLSHADERSOURCEPROC glShaderSource;
extern PFNGLCOMPILESHADERPROC glCompileShader;
extern PFNGLATTACHSHADERPROC glAttachShader;
extern PFNGLLINKPROGRAMPROC glLinkProgram;
extern PFNGLCREATEVERTEXARRAYSPROC glCreateVertexArrays;
extern PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
extern PFNGLBINDVERTEXARRAYPROC glBindVertexArray;

extern PFNGLCLEARBUFFERFVPROC glClearBufferfv;
extern PFNGLUSEPROGRAMPROC glUseProgram;

extern PFNGLCREATEVERTEXARRAYSPROC glDeleteVertexArrays;
extern PFNGLDELETEPROGRAMPROC glDeleteProgram;

extern PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;

extern PFNGLCREATEBUFFERSPROC glCreateBuffers;
extern PFNGLBINDBUFFERPROC glBindBuffer;
extern PFNGLBUFFERSTORAGEPROC glBufferStorage;
extern PFNGLNAMEDBUFFERSTORAGEPROC glNamedBufferStorage;
extern PFNGLBUFFERSUBDATAPROC glBufferSubData;
extern PFNGLNAMEDBUFFERSUBDATAPROC glNamedBufferSubData;

extern PFNGLMAPBUFFERPROC glMapBuffer;
extern PFNGLMAPNAMEDBUFFERPROC glMapNamedBuffer;
extern PFNGLUNMAPBUFFERPROC glUnmapBuffer;
extern PFNGLUNMAPNAMEDBUFFERPROC glUnmapNamedBuffer;
extern PFNGLMAPBUFFERRANGEPROC glMapBufferRange;
extern PFNGLMAPNAMEDBUFFERRANGEPROC glMapNamedBufferRange;

extern PFNGLCLEARBUFFERSUBDATAPROC glClearBufferSubData;
extern PFNGLCLEARNAMEDBUFFERSUBDATAPROC glClearNamedBufferSubData;
extern PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData;
extern PFNGLCOPYNAMEDBUFFERSUBDATAPROC glCopyNamedBufferSubData;

extern PFNGLVERTEXARRAYATTRIBBINDINGPROC glVertexArrayAttribBinding;
extern PFNGLVERTEXARRAYVERTEXBUFFERPROC glVertexArrayVertexBuffer;
extern PFNGLVERTEXARRAYATTRIBFORMATPROC glVertexArrayAttribFormat;
extern PFNGLENABLEVERTEXARRAYATTRIBPROC glEnableVertexArrayAttrib;
extern PFNGLDISABLEVERTEXARRAYATTRIBPROC glDisableVertexArrayAttrib;
extern PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;

extern PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;

extern PFNGLGENBUFFERSPROC glGenBuffers;
extern PFNGLBUFFERDATAPROC glBufferData;
extern PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
extern PFNGLDELETEBUFFERSPROC glDeleteBuffers;
extern PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC glDrawElementsInstancedBaseInstance;
extern PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC glDrawArraysInstancedBaseInstance;

extern PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
extern PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;

extern PFNGLGETSHADERIVPROC glGetShaderiv;
extern PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
extern PFNGLTEXSTORAGE2DPROC glTexStorage2D;

extern PFNGLDELETESHADERPROC glDeleteShader;

extern PFNGLTEXSTORAGE1DPROC glTexStorage1D;
extern PFNGLTEXSTORAGE3DPROC glTexStorage3D;
extern PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
extern PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;

extern PFNGLGENERATEMIPMAPPROC glGenerateMipmap;

static bool LoadModernOpenGL()
{
	if (ModernOpenGLLoaded) return true;

	LOAD_GL_FUNC(glCreateProgram, PFNGLCREATEPROGRAMPROC);
	LOAD_GL_FUNC(glCreateShader, PFNGLCREATESHADERPROC);
	LOAD_GL_FUNC(glShaderSource, PFNGLSHADERSOURCEPROC);
	LOAD_GL_FUNC(glCompileShader, PFNGLCOMPILESHADERPROC);
	LOAD_GL_FUNC(glAttachShader, PFNGLATTACHSHADERPROC);
	LOAD_GL_FUNC(glLinkProgram, PFNGLLINKPROGRAMPROC);
	LOAD_GL_FUNC(glCreateVertexArrays, PFNGLCREATEVERTEXARRAYSPROC);
	LOAD_GL_FUNC(glGenVertexArrays, PFNGLGENVERTEXARRAYSPROC);
	LOAD_GL_FUNC(glBindVertexArray, PFNGLBINDVERTEXARRAYPROC);

	LOAD_GL_FUNC(glClearBufferfv, PFNGLCLEARBUFFERFVPROC);
	LOAD_GL_FUNC(glUseProgram, PFNGLUSEPROGRAMPROC);

	LOAD_GL_FUNC(glDeleteVertexArrays, PFNGLCREATEVERTEXARRAYSPROC);
	LOAD_GL_FUNC(glDeleteProgram, PFNGLDELETEPROGRAMPROC);

	LOAD_GL_FUNC(glVertexAttrib4fv, PFNGLVERTEXATTRIB4FVPROC);

	LOAD_GL_FUNC(glCreateBuffers, PFNGLCREATEBUFFERSPROC);
	LOAD_GL_FUNC(glBindBuffer, PFNGLBINDBUFFERPROC);
	LOAD_GL_FUNC(glBufferStorage, PFNGLBUFFERSTORAGEPROC);
	LOAD_GL_FUNC(glNamedBufferStorage, PFNGLNAMEDBUFFERSTORAGEPROC);
	LOAD_GL_FUNC(glBufferSubData, PFNGLBUFFERSUBDATAPROC);
	LOAD_GL_FUNC(glNamedBufferSubData, PFNGLNAMEDBUFFERSUBDATAPROC);

	LOAD_GL_FUNC(glMapBuffer, PFNGLMAPBUFFERPROC);
	LOAD_GL_FUNC(glMapNamedBuffer, PFNGLMAPNAMEDBUFFERPROC);
	LOAD_GL_FUNC(glUnmapBuffer, PFNGLUNMAPBUFFERPROC);
	LOAD_GL_FUNC(glUnmapNamedBuffer, PFNGLUNMAPNAMEDBUFFERPROC);
	LOAD_GL_FUNC(glMapBufferRange, PFNGLMAPBUFFERRANGEPROC);
	LOAD_GL_FUNC(glMapNamedBufferRange, PFNGLMAPNAMEDBUFFERRANGEPROC);

	LOAD_GL_FUNC(glClearBufferSubData, PFNGLCLEARBUFFERSUBDATAPROC);
	LOAD_GL_FUNC(glClearNamedBufferSubData, PFNGLCLEARNAMEDBUFFERSUBDATAPROC);
	LOAD_GL_FUNC(glCopyBufferSubData, PFNGLCOPYBUFFERSUBDATAPROC);
	LOAD_GL_FUNC(glCopyNamedBufferSubData, PFNGLCOPYNAMEDBUFFERSUBDATAPROC);

	LOAD_GL_FUNC(glVertexArrayAttribBinding, PFNGLVERTEXARRAYATTRIBBINDINGPROC);
	LOAD_GL_FUNC(glVertexArrayVertexBuffer, PFNGLVERTEXARRAYVERTEXBUFFERPROC);
	LOAD_GL_FUNC(glVertexArrayAttribFormat, PFNGLVERTEXARRAYATTRIBFORMATPROC);
	LOAD_GL_FUNC(glEnableVertexArrayAttrib, PFNGLENABLEVERTEXARRAYATTRIBPROC);
	LOAD_GL_FUNC(glDisableVertexArrayAttrib, PFNGLDISABLEVERTEXARRAYATTRIBPROC);
	LOAD_GL_FUNC(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAYPROC);
	LOAD_GL_FUNC(glDisableVertexAttribArray, PFNGLDISABLEVERTEXATTRIBARRAYPROC);

	LOAD_GL_FUNC(glGetAttribLocation, PFNGLGETATTRIBLOCATIONPROC);

	LOAD_GL_FUNC(glGenBuffers, PFNGLGENBUFFERSPROC);
	LOAD_GL_FUNC(glBufferData, PFNGLBUFFERDATAPROC);
	LOAD_GL_FUNC(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTERPROC);
	LOAD_GL_FUNC(glDeleteBuffers, PFNGLDELETEBUFFERSPROC);
	LOAD_GL_FUNC(glDrawElementsInstancedBaseInstance, PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC);
	LOAD_GL_FUNC(glDrawArraysInstancedBaseInstance, PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC);

	LOAD_GL_FUNC(glUniformMatrix4fv, PFNGLUNIFORMMATRIX4FVPROC);
	LOAD_GL_FUNC(glGetUniformLocation, PFNGLGETUNIFORMLOCATIONPROC);

	LOAD_GL_FUNC(glGetShaderiv, PFNGLGETSHADERIVPROC);
	LOAD_GL_FUNC(glGetShaderInfoLog, PFNGLGETSHADERINFOLOGPROC);
	LOAD_GL_FUNC(glTexStorage2D, PFNGLTEXSTORAGE2DPROC);

	LOAD_GL_FUNC(glDeleteShader, PFNGLDELETESHADERPROC);

	LOAD_GL_FUNC(glTexStorage1D, PFNGLTEXSTORAGE1DPROC);
	LOAD_GL_FUNC(glTexStorage3D, PFNGLTEXSTORAGE3DPROC);
	LOAD_GL_FUNC(glTexSubImage3D, PFNGLTEXSUBIMAGE3DPROC);
	LOAD_GL_FUNC(glCompressedTexImage2D, PFNGLCOMPRESSEDTEXIMAGE2DPROC);

	LOAD_GL_FUNC(glGenerateMipmap, PFNGLGENERATEMIPMAPPROC);

	ModernOpenGLLoaded = true;
	return true;
}